# Generated by Django 3.0 on 2019-12-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jstree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('appname', models.CharField(max_length=255)),
                ('treemodelname', models.CharField(max_length=255)),
                ('leafmodelname', models.TextField(blank=True, default='')),
                ('applyTypes', models.BooleanField(default=False, help_text="If checked, the method 'getJSTreeType()' will be called on each node in the tree and added to the type parameter on each node.", verbose_name='Add node type?')),
                ('contextMenu', models.BooleanField(default=False, help_text='Enabling this option requires you to define the context menu based on the node type.', verbose_name='Enable Context Menu Popup?')),
                ('enableSearch', models.BooleanField(default=False, verbose_name='Enable search functionality for this tree?')),
                ('enableFuzzySearch', models.BooleanField(default=False, verbose_name='Turn on fuzzy (non-exact) searching and highlighting using simple pattern matching')),
                ('enableCheckbox', models.BooleanField(default=False, verbose_name='Add checkboxes before node?')),
                ('enableDND', models.BooleanField(default=False, help_text='Enabling this option requires additional Javascript to make it do anything', verbose_name='Enable drag and drop functionality')),
                ('enableState', models.BooleanField(default=False, help_text="Remember if the nodes' state the last time this tree was used.", verbose_name='Remember Node State?')),
                ('enableUnique', models.BooleanField(default=False, verbose_name='Require unique names of sibling nodes?')),
                ('enableWholeRow', models.BooleanField(default=False, help_text='May cause slowness for large trees or on older browsers.', verbose_name='Allow click on and highlight whole row when selecting nodes?')),
                ('additionalJS', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='nodeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('maxChildren', models.IntegerField(default=-1, verbose_name='Maximum number of child nodes for this type (-1 unlimited)')),
                ('maxDepth', models.IntegerField(default=-1, verbose_name='Maximum depth of children for this node type (-1 unlimited)')),
                ('childNodeTypes', models.ManyToManyField(to='django_jstree.nodeType')),
                ('jsTree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_jstree.jstree')),
            ],
        ),
    ]
