# Generated by Django 3.0 on 2019-12-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jstree',
            name='leafmodelname',
        ),
        migrations.AddField(
            model_name='jstree',
            name='leaffieldname',
            field=models.TextField(blank=True, default='', help_text='Name of one or more fields defined in the model which represent a leaf relationship.', verbose_name="Field names of one or more 'leaf' relation fields seperated by commas. (ex. leaf1field[,leaf2field,leafthreefield])"),
        ),
    ]
