# Generated by Django 3.0.1 on 2019-12-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0002_auto_20191227_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jstree',
            old_name='enableWholeRow',
            new_name='enableWholerow',
        ),
        migrations.AddField(
            model_name='jstree',
            name='enableChanged',
            field=models.BooleanField(default=False, help_text='This plugin adds additional information about selection changes.', verbose_name='Add additonal change info?'),
        ),
        migrations.AddField(
            model_name='jstree',
            name='enableSort',
            field=models.BooleanField(default=False, help_text='Automaticly sort sibling nodes in alphabetical order.', verbose_name='Sort Nodes?'),
        ),
        migrations.AddField(
            model_name='jstree',
            name='showOnlyMatches',
            field=models.BooleanField(default=False, verbose_name='Only show matches when searching?'),
        ),
        migrations.AddField(
            model_name='jstree',
            name='showOnlyMatchesChildren',
            field=models.BooleanField(default=False, verbose_name='Show the children of matches when searching?'),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='aAttributes',
            field=models.TextField(blank=True, default='', help_text='Additional attributes to add to the generated A element', verbose_name='A Attributes'),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='iconClass',
            field=models.CharField(blank=True, default='', help_text='CSS class name to add to nodes of this type', max_length=30, verbose_name='CSS class'),
        ),
        migrations.AddField(
            model_name='nodetype',
            name='liAttributes',
            field=models.TextField(blank=True, default='', help_text='Additional attributes to add to the generated LI element', verbose_name='LI Attributes'),
        ),
        migrations.AlterField(
            model_name='jstree',
            name='enableSearch',
            field=models.BooleanField(default=False, verbose_name='Enable search?'),
        ),
        migrations.AlterField(
            model_name='jstree',
            name='leaffieldname',
            field=models.TextField(blank=True, default='', help_text='Name of one or more fields defined in the model which represent a leaf relationship, seperated by commas. ex. leaf1field[,leaf2field,leafthreefield]', verbose_name='Leaf fields'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='childNodeTypes',
            field=models.ManyToManyField(help_text='Restricts the type of children this node can have (leave empty for no restrictions)', to='django_jstree.nodeType', verbose_name='Valid Child Node Types'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='jsTree',
            field=models.ForeignKey(help_text='Apply this type to these trees.', on_delete=django.db.models.deletion.CASCADE, to='django_jstree.jstree', verbose_name='Trees'),
        ),
    ]
