# Generated by Django 3.0.1 on 2019-12-29 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0003_auto_20191228_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jstree',
            old_name='contextMenu',
            new_name='enableContextmenu',
        ),
    ]
