# Generated by Django 3.0.1 on 2019-12-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0004_auto_20191228_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='childNodeTypes',
            field=models.ManyToManyField(help_text='Restricts the type of children this node can have (select none for no restrictions)', to='django_jstree.nodeType', verbose_name='Valid Child Node Types'),
        ),
        migrations.RemoveField(
            model_name='nodetype',
            name='jsTree',
        ),
        migrations.AddField(
            model_name='nodetype',
            name='jsTree',
            field=models.ManyToManyField(help_text='Apply this type to these trees.', to='django_jstree.jstree', verbose_name='Trees'),
        ),
    ]
