# Generated by Django 3.0 on 2019-12-30 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0005_auto_20191229_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodeTypePopupMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayOrder', models.IntegerField(default=0, help_text='Order to display in on popup Menu', verbose_name='Display order')),
            ],
            options={
                'ordering': ['displayOrder'],
            },
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='childNodeTypes',
            field=models.ManyToManyField(blank=True, help_text='Restricts the type of children this node can have (select none for no restrictions)', to='django_jstree.nodeType', verbose_name='Valid Child Node Types'),
        ),
        migrations.CreateModel(
            name='popupMenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, default='')),
                ('menuText', models.CharField(blank=True, default='', help_text='Text to show on popup menu', max_length=255, verbose_name='Menu Text')),
                ('menuTextClass', models.CharField(blank=True, default='', help_text='CSS Class to apply to menu text', max_length=255, verbose_name='Menu Text Class')),
                ('menuClickJSFunction', models.CharField(blank=True, default='', help_text='Name of Javascript function to call on click', max_length=255, verbose_name='Call on click')),
                ('nodeTypes', models.ManyToManyField(blank=True, help_text='This popup menu item will apply to this node type', through='django_jstree.nodeTypePopupMenuItem', to='django_jstree.nodeType', verbose_name='Apply to Node Types:')),
            ],
        ),
        migrations.AddField(
            model_name='nodetypepopupmenuitem',
            name='nodeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_jstree.nodeType'),
        ),
        migrations.AddField(
            model_name='nodetypepopupmenuitem',
            name='popupMenuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_jstree.popupMenuItem'),
        ),
    ]
