# Generated by Django 3.0.1 on 2020-01-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0008_auto_20191231_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmenuitem',
            name='childMenuItems',
            field=models.ManyToManyField(blank=True, to='django_jstree.popupMenuItem', verbose_name='Child Menu Items'),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='path',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jstree',
            name='applyTypes',
            field=models.BooleanField(default=False, help_text="If checked, the method 'getTreeNodeType()' will be called on each node in the tree and added to the type parameter on each node. If the function does not exist on the model, then the name of the model class is added to type parameter", verbose_name='Add node type?'),
        ),
    ]
