# Generated by Django 3.0.1 on 2020-01-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0009_auto_20200102_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupmenuitem',
            name='nodeTypes',
            field=models.ManyToManyField(blank=True, help_text='This popup menu item will apply to this node type', related_name='popupMenuItems', through='django_jstree.nodeTypePopupMenuItem', to='django_jstree.nodeType', verbose_name='Apply to Node Types:'),
        ),
    ]
