# Generated by Django 3.0.1 on 2020-01-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0010_auto_20200104_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupmenuitem',
            old_name='menuTextClass',
            new_name='menuItemClass',
        ),
        migrations.RenameField(
            model_name='popupmenuitem',
            old_name='menuText',
            new_name='menuLabel',
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='menuTitle',
            field=models.CharField(blank=True, default='', help_text='Help text to show for menu item', max_length=255, verbose_name='Tooltip'),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='seperatorAfter',
            field=models.BooleanField(default=False, help_text='Show a seperator after this menu item', verbose_name='Seperator After?'),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='seperatorBefore',
            field=models.BooleanField(default=False, help_text='Show a seperator before this menu item', verbose_name='Seperator Before?'),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='shortcut',
            field=models.SmallIntegerField(default=0, help_text='KeyCode which will trigger the action if the menu is open (for example 113 for rename, which equals F2)', verbose_name='Shortcut Keycode'),
        ),
        migrations.AddField(
            model_name='popupmenuitem',
            name='shortcutLabel',
            field=models.CharField(blank=True, default='', help_text='Shortcut label (like for example F2 for rename)', max_length=20, verbose_name='Shortcut Label'),
        ),
    ]
