# Generated by Django 3.0.1 on 2020-01-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jstree', '0011_auto_20200104_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupmenuitem',
            old_name='menuTitle',
            new_name='menuTooltip',
        ),
    ]
